"""phase C: verifications + reviews + chamber sessions

Revision ID: 28e9c4a069e8
Revises: a376ab1ca234
Create Date: 2026-05-23 17:34:23.517303
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '28e9c4a069e8'
down_revision: Union[str, None] = 'a376ab1ca234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamber_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('consent_id', sa.UUID(), nullable=True),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chamber_address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('fee_bdt', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=16), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('ai_summary_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_by', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("payment_status IN ('pending','paid','refunded','failed')", name='ck_verification_requests_payment_status'),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_requests_doctor_status', 'verification_requests', ['doctor_id', 'payment_status'], unique=False)
    op.create_index('ix_verification_requests_patient', 'verification_requests', ['patient_id', 'created_at'], unique=False)
    op.create_table('doctor_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_doctor_reviews_rating'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_id')
    )
    op.create_index('ix_doctor_reviews_doctor', 'doctor_reviews', ['doctor_id'], unique=False)
    op.create_table('verification_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.Column('ai_claims_eval', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('doctor_notes_bn', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("disposition IN ('agree','concerns','escalate')", name='ck_verification_reviews_disposition'),
    sa.ForeignKeyConstraint(['request_id'], ['verification_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_reviews')
    op.drop_index('ix_doctor_reviews_doctor', table_name='doctor_reviews')
    op.drop_table('doctor_reviews')
    op.drop_index('ix_verification_requests_patient', table_name='verification_requests')
    op.drop_index('ix_verification_requests_doctor_status', table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_table('chamber_sessions')
    # ### end Alembic commands ###
