"""docs module tables

Revision ID: a9b5d9e308af
Revises: c5f4e8d20a17
Create Date: 2026-05-30 20:55:58.167587
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9b5d9e308af'
down_revision: Union[str, None] = 'c5f4e8d20a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_key')
    )
    op.create_index('ix_docs_sections_order', 'docs_sections', ['order'], unique=False)
    op.create_table('docs_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_docs_team_members_order', 'docs_team_members', ['order'], unique=False)
    op.create_table('docs_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('pending_signups_phone_idx'), table_name='pending_signups')
    op.create_index(op.f('ix_pending_signups_phone'), 'pending_signups', ['phone'], unique=False)
    op.drop_index(op.f('users_email_idx'), table_name='users', postgresql_where='(email IS NOT NULL)')

    # Insert default config (June 10-14, 2026 - ICADHI judging window)
    op.execute("""
        INSERT INTO docs_config (id, is_public, start_datetime, end_datetime)
        VALUES (1, false, '2026-06-10 00:00:00+00', '2026-06-14 23:59:59+00')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=False, postgresql_where='(email IS NOT NULL)')
    op.drop_index(op.f('ix_pending_signups_phone'), table_name='pending_signups')
    op.create_index(op.f('pending_signups_phone_idx'), 'pending_signups', ['phone'], unique=False)
    op.drop_table('docs_config')
    op.drop_index('ix_docs_team_members_order', table_name='docs_team_members')
    op.drop_table('docs_team_members')
    op.drop_index('ix_docs_sections_order', table_name='docs_sections')
    op.drop_table('docs_sections')
    # ### end Alembic commands ###
