"""init: users, otp_codes, patient_profiles, doctor_profiles, documents

Revision ID: d99530cae0c6
Revises: 
Create Date: 2026-05-23 14:54:23.843463
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd99530cae0c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('phone')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('patient','doctor','admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('doctor_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bmdc_number', sa.String(length=32), nullable=False),
    sa.Column('qualifications', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('specialties', postgresql.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('fee_tier', sa.Integer(), nullable=False),
    sa.Column('chambers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('device_id_hash', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.CheckConstraint('fee_tier IN (1,2,3)', name='ck_doctor_profiles_fee_tier'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('bmdc_number')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.CheckConstraint("kind IN ('prescription','lab_report','discharge','other')", name='ck_documents_kind'),
    sa.CheckConstraint("source IN ('patient_upload','doctor_added')", name='ck_documents_source'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.CheckConstraint("sex IN ('M','F','O')", name='ck_patient_profiles_sex'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_documents_patient_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('doctor_profiles')
    op.drop_table('users')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
